### ISSUE TITLE
Support for Topic Icon on Index extension

### ISSUE THREAD

**Issue by renzotom** [kinerity/bestanswer#2]
Can you add support for that extension please? There is error with it on 3.2.2 version. Link to extension: https://www.phpbb.com/customise/db/extension/topic_icon_on_index/support/topic/187541 (PS: I reported it here, what error is there).

**Comment by kinerity** [comment]
They need to check if TOPICS_TABLE is already aliased. Best Answer already does this [(](https://github.com/kinerity/bestanswer/blob/master/event/main_listener.php#L204-L210)[)]
